spring.application.name=Readx
server.port=8082

# ====== DATABASE CONFIG - Railway Environment Variables ======
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ====== EMAIL CONFIG ======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rakesh@gmail.com
spring.mail.password=uyuhsmwyeqqlphgu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ====== RAZORPAY ======
razorpay.key.id=rzp_test_SwMTMsVbQxARmd

razorpay.key.secret=sSs5pPNloSP0jLnNalP0MFcb

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

